TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# Low-level stats displays
EDL += ioc_stats.edl
EDL += ioc_stats_clust.edl
EDL += ioc_stats_epics_env.edl
EDL += ioc_stats_limits.edl
EDL += ioc_stats_reboot_confirm.edl
EDL += ioc_stats_release.edl
EDL += ioc_stats_reloadacf_confirm.edl
EDL += ioc_stats_scanmon.edl
EDL += ioc_stats_soft.edl
EDL += ioc_stats_vxworks.edl

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
